/**
 * Generated by scripts/write-config.ts -- do not edit by hand.
 * Chain: 10143
 * Deployed: 2026-10-06T14:43:14.817Z
 * Built from commit: ba9f84e325cedeb6e04fd29fc8f5dfa6a0697bcc
 */
import { ERC8004 } from "./chain.ts";

export const ADDRESSES = {
  cardManager: "0xb8e3963261d0A81E4009b6c71470294552093ffA",
  spendGate: "0x11d4f6fe7ea9320106145d4f50e6b0122A42d20F",
  spendRouter: "0xe7126777E8aAFE384F32854b3AB7A518561625D2",
  mockMerchantA: "0x7169dE5dd003bD2E6906e1D36672eE260F96Df8A",
  mockMerchantB: "0xf0F4219338Ca10615973b2522ad07FBA0cdD7E83",
  mockMerchantC: "0x9E4D51a114Ae490A86BddB1c421BAEd56Bf867BE",
  reputationReader: "0x20B66005E757684cfF642D7c5722610aB1E469C1",
  /** Settlement token: real AUSD on this chain, not a mock we deployed. */
  paymentToken: "0xa9012a055bd4e0eDfF8Ce09f960291C09D5322dC",
  ausdFaucet: "0xd236c18D274E54FAccC3dd9DDA4b27965a73ee6C",
  ...ERC8004,
} as const;

export const DEPLOYMENT = {
  chainId: 10143,
  commit: "ba9f84e325cedeb6e04fd29fc8f5dfa6a0697bcc",
  deployedAt: "2026-10-06T14:43:14.817Z",
} as const;
